In [18]:
import torch
import numpy as np
from torch import nn
from torch.nn import functional as F
import time

In [19]:
#Dot Product / Matrix Multiplication
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [20]:
#Floats and Ints cannot mix unless you cast float onto int.
#Matrix multiplications will be done with floating point numbers and not ints
#Type int64
int_64 = torch.randint(1,(3,2)).float()

#Type float32
float_32 = torch.rand(2,3)
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [22]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T, C)
print(output)

tensor([[0.3681, 0.0681, 0.9953, 0.6885, 0.5519, 0.2278, 0.8080, 0.5416, 0.9402,
         0.3494],
        [0.8507, 0.8289, 0.4053, 0.3689, 0.9746, 0.3526, 0.2440, 0.1274, 0.2544,
         0.6990],
        [0.1466, 0.6685, 0.4365, 0.9042, 0.3028, 0.5098, 0.4139, 0.8276, 0.3775,
         0.4359],
        [0.0269, 0.7291, 0.1404, 0.4072, 0.9516, 0.0581, 0.3840, 0.2511, 0.7141,
         0.3435],
        [0.3443, 0.3366, 0.8969, 0.8327, 0.0859, 0.5770, 0.6745, 0.0613, 0.5130,
         0.1053],
        [0.6970, 0.3124, 0.7912, 0.2009, 0.8615, 0.1673, 0.0625, 0.5842, 0.8877,
         0.9886],
        [0.3761, 0.5908, 0.6295, 0.4112, 0.7248, 0.4764, 0.8086, 0.5070, 0.1592,
         0.2688],
        [0.8931, 0.8273, 0.9416, 0.1351, 0.1134, 0.6491, 0.6231, 0.9604, 0.5103,
         0.9535],
        [0.0875, 0.1524, 0.0794, 0.7517, 0.4767, 0.8731, 0.8463, 0.7667, 0.5602,
         0.7048],
        [0.5222, 0.8755, 0.8247, 0.5158, 0.5008, 0.8474, 0.1100, 0.5264, 0.5009,
         0.0362],
        [0

In [47]:
x = torch.tensor([-0.05], dtype=torch.float32)

n = nn.ReLU()

#What RELU does:
#If a number is 0 or below 0 it will turn the num into 0
#If it's above 0 it will stay the same
#It is a non-linear activation function

#ReLU is Rectified Linear Unit - Direct Shape, not S curve
#Range: [0,infinity]
y = n(x)
print(y)

tensor([0.])


In [48]:
#Sigmoid Non-Linear Activation Function
#Turns any number into a value between 0 and 1

#Sigmoid has an S-shape curve
#Range: [0,1]
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [49]:
#Tanh Non-Linear Activation Function
#Turns any real value number into a range between -1 and 1

#Tanh has an almost S-shape curve like Sigmoid but different ranges
#Range: [-1,1]
y = F.tanh(x)
print(y)

tensor([-0.0500])
